app = "dev-digest-courier-api"

[build]
  [build.args]
    START_CMD = "node dist/index.js"

[mounts]
  source = "logs_data"
  destination = "/app/logs"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
