app = "dev-digest-courier-worker"

[build]
  [build.args]
    START_CMD = "node dist/worker.js"

[mounts]
  source = "logs_data"
  destination = "/app/logs"

[[services]]
  auto_stop_machines = false
  auto_start_machines = true
